#!C:/Program\ Files/Git/usr/bin/sh.exe
#
# A hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# Check for files that should never be committed 

#echo "---- PRE COMMIT HOOK ----"

# file names to never commit
fileNameRegex='(publish.bat|Data processing procedure.docx)$'

while read st file; do
    # skip files not added
    if [ "$st" != 'A' ]; then continue; fi

    if [[ $file =~ $fileNameRegex ]]; then
        echo "File forbidden: $file"
        echo "You can force the commit with the --no-verify argument if needed."
        exit 1
    fi
done < <(git diff --cached --name-status)
